### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by designgears** [brandonxiang/Leaflet.PictureMarker#1]
This defeats the purpose of using the canvas. 

It should batch draw the markers, then redraw the canvas, redraw on every marker is very slow.

Also, when it calculates the middle of the image you should always round up, otherwise you risk chopping the edge of the marker off, happens with the provided marker image.

**Comment by brandonxiang** [comment]
How many markers did you place on map?

**Comment by designgears** [comment]
Around 2000, but slow down from redrawing is obvious even with less than 100.

**Comment by brandonxiang** [comment]
It is no problem on [draw 1000 points](https://brandonxiang.github.io/Leaflet.PictureMarker/examples/multi-point.html). Would you mind posting your code on fiddler ?

**Comment by designgears** [comment]
Really odd, works perfectly at home, it chokes on my work computer, not sure why, the hardware is more than capable. Closing, seems to be an issue on my end.

Thanks for taking the time to look into it and provide a larger example.
